Add csrf and update submit post
ONSdigital/eq-performance-test pull request #15
Opened 2017-03-10 15:34 UTC by benjefferies

### What is the context of this PR?
1. Extracting csrf token
1. Add csrf token to request body
1. Update submit to post to next block

### How to review
1. Run survey runner in debug
1. Run performance test against $host with one user
```
docker run \                                   
    -e HOST=$host \
    -e PROTOCOL=http \
    -e PORT=5000 \
    -e USERS=1 \
    -e REPEAT=1 \
    -v ~/testResults:/eq-performance-test/results \
   eq-performance-test
```
1. Check all POSTs but one is valid and answers are submitted

2017-03-10 15:39 UTC, collisdigital commented on survey_runner_jmeter.rb
> +        extract_csrf
Any need to extract it; survey should be finished now?

2017-03-10 15:44 UTC, benjefferies commented on survey_runner_jmeter.rb
> +        extract_csrf
Nope just got copy-paste happy

2017-03-10 16:20 UTC, collisdigital approved these changes
Ran locally 500 users; all succeeded. Might be worth adding to README.md that you should use lo0 via ifconfig on a Mac?

2017-03-10 16:39 UTC, benjefferies commented
Fair point @collisdigital. Done.

2017-03-13 11:31 UTC, ajmaddaford requested changes
When I run it I get a failure:
`1489402400026|26|POST page 1 (filled)|200|OK|ThreadGroup 1-1|false|Test failed: text expected to contain /Your responses/|10188|1|1|26|1|1|null`

2017-03-13 12:26 UTC, ajmaddaford approved these changes
I hadn't run docker build! Works for me now 😃

2017-03-13 12:26 UTC, merged